on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Console
        run: cd console/react && npm install

      - name: Run Tests
        run: cd console/react && npm run test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Console
        run: cd console/react && npm install

      - name: Install Typescript
        run: cd console/react && npm install typescript

      - name: Run ESLint
        run: cd console/react && npx eslint --max-warnings 0 .
